# Generated by Django 3.2.9 on 2021-11-21 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='task',
            order_with_respect_to='task_status',
        ),
    ]
